CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) UNIQUE NOT NULL,
    FullName VARCHAR(255),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PracticeSessions (
    SessionID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    SessionStart DATETIME DEFAULT CURRENT_TIMESTAMP,
    SessionEnd DATETIME,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Shots (
    ShotID INT AUTO_INCREMENT PRIMARY KEY,
    SessionID INT NOT NULL,
    ShotTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    ShotPositionX DECIMAL(10, 2) NOT NULL,
    ShotPositionY DECIMAL(10, 2) NOT NULL,
    Result ENUM('Made', 'Missed') NOT NULL,
    FOREIGN KEY (SessionID) REFERENCES PracticeSessions(SessionID)
);
